openapi: 3.0.3
info:
  title: OnboArding API
  version: 1.0.0
  description: STD22117
  contact:
    email: hei.diary.2@gmail.com
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: students
    description: Everything about HEI Students.
  - name: teachers
    description: Everything about HEI Teachers.
    
paths:
  /students:
    post:
      tags:
        - students
      summary: Ajouter un nouvel étudiant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentInput'
      
    get:
      tags:
        - students
      summary: Get the Students list
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Students'
      
    
    delete:
      tags:
        - user
      
components:
  schemas:
    Students:
      type: array
      